#ifndef __UPDATE__
#define __UPDATE__

#include "models/board.h"
#include "models/move.h"


/*
 * Update the state of the board for a given side after making a move.
 * (WARNING) The function cannot receive a generated move and an input move at
 * the same time.
 * @params: board -> pointer to a board object
 *          side -> side for which the engine is playing
 *          in_move -> move received from XBoard
 *          gen_move -> move generated by the engine
 * @returns: no return
 */
void update(board_t *board, side_t side, move_t in_move, move_t gen_move);


#endif